CC = gcc
CFLAGS = -static
TARGETS = test_pidtoname
# test_topuser test_timeuser test_kernelps \
	test_freeblocks
all:
# pidtoname:
	gcc -static test_pidtoname.c -o ./test_pidtoname

clean:
	rm $(TARGETS)
